### ISSUE TITLE
Failed to read git object

### ISSUE THREAD

**Issue by Zekdar** [47ng/actions-clever-cloud#108]
Hi,

I'm having the following error when my 47ng/actions-clever-cloud@v1 job is running :

```
Remote git head commit   is ...a9c7e
Current deployed commit  is ...a9c7e
New local commit to push is ...dbd47 (from refs/heads/dev)
Error:  Failed to read git object with oid ...5e06a
Error: The process '/action/node_modules/.bin/clever' failed with exit code 1
```
There's not much explanation in the error message. Do you know what could be the problem ?

Thanks

**Comment by franky47** [comment]
This looks like your working copy is not fully checked out (Clever Cloud does not work with shallow working copies).

Have you run the prerequisite `git fetch --prune --unshallow` before invoking the action ?

**Comment by Zekdar** [comment]
Indeed, I forgot that prerequisite.
Thanks !
