### ISSUE TITLE
Deployment failure for rejected push (not fast forward) should fail the workflow

### ISSUE THREAD

**Issue by rik** [47ng/actions-clever-cloud#187]
We're seeing the following error in our workflows but they don't fail the workflow.
```
Error:  Push rejected because it was not a simple fast-forward. Use "force: true" to override.
```

I'm not sure if #184 was supposed to catch those. We're using v1.1.

**Comment by franky47** [comment]
It looks like deployment failure detection is not as reliable as it was, I also had aborted deployments marked as successful. I'll look into it.

Your issue mentions failure because of a non-linear commit history, I was thinking of adding a `force` option to pass to Clever Cloud, would that be useful? I'm thinking about staging environments where branching can often be non-linear (eg: switching from a feature preview to another).

**Comment by rik** [comment]
> I was thinking of adding a force option to pass to Clever Cloud, would that be useful?

Yes it would. We [started implementing that option](https://github.com/47ng/actions-clever-cloud/compare/master...rik:allow-force) but had issues verifying that it works in an actual workflow.

**Comment by franky47** [comment]
I see, I'll gladly review that PR once it's ready. What were your issues?

**Comment by rik** [comment]
We were struggling to run our code because of the Docker image in https://github.com/47ng/actions-clever-cloud/blob/b4c20df952b2643e724b0cc8e4f944b6b53b7b31/action.yml#L39. In the end, we just changed that line to `image: 'Dockerfile'`.

PR submitted: https://github.com/47ng/actions-clever-cloud/pull/188 but I think this issue should stay open as it is two separate problems.

**Comment by mockersf** [comment]
I tried using this option but couldn't just use the latest master version of this repo because of the docker image.

Could you tag an updated version of the docker image and push a new version of the action with it?

**Comment by rik** [comment]
Thanks!

I think the particular issue should stay open though because it is . My patch gives an option to force deploys regardless of the fast-forwardable state but the original problem is: if a deploy fails because it can't fast-forward, the action will not fail the workflow.
