### ISSUE TITLE
Is it possible to use --force option ?

### ISSUE THREAD

**Issue by anthonylegoas** [47ng/actions-clever-cloud#50]
Hey, first of all, thanks for your work ! ;)

I have a question, is it possible to use the `--force` when executing `clever deploy` ?

Actually, I can't deploy to Clever Cloud because of the following error:
`
/action/node_modules/.bin/clever deploy --alias xxx
...
[ERROR] Push rejected because it was not a simple fast-forward. Use "--force" to override.
##[error]The process '/action/node_modules/.bin/clever' failed with exit code 1
`

**Comment by anthonylegoas** [comment]
I resolved my error, using directly the clever-cloud CLI with the `--force` option, it will be fine now.
I close this issue.
Maybe, it could be nice to allow the use of the `--force` option with this github action ? Or not, not very secure.

**Comment by franky47** [comment]
You only need to use `--force` when pushing a new Git history to an existing application (eg: moving a deployed application from a monorepo to its own repository), I don't think it's something that should be automated, and you are right in the security concern.

**Comment by stem** [comment]
Hey all

@epicery, we're using a rebased branch `staging` for the, well, staging version of our application. It is constantly rebased, merged against multiple WIP branches and considered throwable at any moment if necessary.
At the end of the day, we push it to clever cloud using a `--force` option and would really like to automate it with this action.

Of course, the `master` branch consists only of fast forward pushes so it would not be `--force`d when deployed.

Would you consider a PR for this functionality ?

**Comment by franky47** [comment]
I'm open to a PR, we can discuss API details there. It needs to be fairly obvious in the docs that using `--force` can be dangerous.

**Comment by stem** [comment]
Never mind, I've set it up with : 
```
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: git remote add clever https://${{ secrets.CLEVER_TOKEN }}:${{ secrets.CLEVER_SECRET }}@push-par-clevercloud-customers.services.clever-cloud.com/APP_ID.git
      - run: git fetch clever
      - run: git push clever HEAD:master --force
```

**Comment by rik** [comment]
For anyone reading this, there is now a [`force: true` option since `v1.2`](https://github.com/47ng/actions-clever-cloud#force-deployement).
